from pathlib import Path
p=Path('server/src/controllers/auth.controller.ts');s=p.read_text();a=s.index('    const { data, error } = await supabase.auth.admin.createUser');b=s.index('    if (error || !data.user)',a);s=s[:a]+'''    const existing = await supabase.from('profiles').select('id').eq('email',email).maybeSingle();
    if(existing.error) throw new AppError('Unable to check account',503);
    if(existing.data) throw new AppError('An account with this email already exists',409);
    const { data, error } = await createAuthClient().auth.signUp({
      email,password,options:{data:{first_name:firstName,last_name:lastName},emailRedirectTo:`${env.CLIENT_URL}/login`},
    });
'''+s[b:];a=s.index('    const confirmation =');b=s.index('    await session(req, res, profile, 201);',a);s=s[:a]+s[b:];p.write_text(s)
p=Path('server/src/routes/team.routes.ts');s=p.read_text();s="import { env } from '../config/env';\n"+s;s=s.replace("{data:{first_name:firstName,last_name:lastName}}", "{data:{first_name:firstName,last_name:lastName},redirectTo:`${env.CLIENT_URL}/reset-password`}");p.write_text(s)
p=Path('client/src/components/common/LiveData.tsx');s=p.read_text();s=s.replace("options?:string[]", "options?:Array<string|{value:string;label:string}>");s=s.replace("f.type==='number'?Number(v):v", "f.type==='number'?Number(v):f.type==='datetime-local'?new Date(String(v)).toISOString():v");s=s.replace("{f.options.map(o=><option key={o}>{o}</option>)}", "{!f.required&&<option value=\"\">Not selected</option>}{f.options.map(o=>typeof o==='string'?<option key={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}");s=s.replace("const allColumns=actions?", "const customers=useLiveQuery(['customers'],()=>readList('/customers'),Boolean(fields)&&['/tasks','/appointments'].includes(path));\n  const formFields=fields&&['/tasks','/appointments'].includes(path)?[...fields,{key:'customerId',label:'Customer',options:(customers.data||[]).map(c=>({value:c.id,label:name(c)}))}]:fields;\n  const allColumns=actions?");s=s.replace('<RecordForm fields={fields}', '<RecordForm fields={formFields!}');p.write_text(s)
p=Path('client/src/services/liveData.ts');s=p.read_text().replace("  window.dispatchEvent(new Event('crm:data-changed'));\n",'');p.write_text(s)
p=Path('client/src/pages/app/LeadsPage.tsx');s=p.read_text();s="import { useAuthStore } from '@/store/authStore';\n"+s;s=s.replace('  const navigate = useNavigate();','  const navigate = useNavigate();\n  const activeDealershipId = useAuthStore(s=>s.activeDealershipId);');s=s.replace("queryKey: ['leads', selectedStage, selectedTemperature]", "queryKey: [activeDealershipId, 'leads', selectedStage, selectedTemperature, window.location.search]");s=s.replace('placeholder="Customer visited lot looking for 2024 Camry or midsize sedan..."','placeholder="Add the customer’s request or relevant notes"');p.write_text(s)
p=Path('client/src/pages/auth/RegisterPage.tsx');s=p.read_text().replace("label: 'Invite Team'", "label: 'Finish setup'").replace("    inviteEmail1: '',\n    inviteRole1: 'salesperson',\n    inviteEmail2: '',\n    inviteRole2: 'manager',",'');p.write_text(s)
p=Path('client/src/App.tsx');s=p.read_text().replace("Routes, Route, Navigate", "Routes, Route, Navigate, useLocation");s=s.replace("function PublicOnlyRoute({ children }: { children: React.ReactNode }) {", "function PublicOnlyRoute({ children }: { children: React.ReactNode }) {\n  const location=useLocation();");s=s.replace("  if (isAuthenticated) {\n    if (role", "  if (isAuthenticated) {\n    if (!role) return location.pathname === '/register' ? <>{children}</> : <Navigate to=\"/register\" replace/>;\n    if (role");p.write_text(s)
# Allow a real account without a dealership to resume setup without registering twice.
p=Path('client/src/pages/auth/RegisterPage.tsx');s=p.read_text().replace('const [registered, setRegistered] = useState<any>(null);',"const [registered, setRegistered] = useState<any>(()=>{const state=useAuthStore.getState();return state.isAuthenticated?{user:state.user,accessToken:state.accessToken}:null;});");p.write_text(s)
